import { def } from "../togm";
import { CreateNode, createNodes, createRelationships } from "../update";

export const northwindGraph = () =>
  def.graph({
    Product: def.node({
      unitPrice: def.number(),
      unitsInStock: def.number(),
      reorderLevel: def.number(),
      discontinued: def.boolean(),
      quantityPerUnit: def.string(),
      productName: def.string(),
      unitsOnOrder: def.number(),
      category: def.oneOut("PART_OF", "Category"),
      suppliers: def.manyIn("SUPPLIES", "Supplier"),
    }),
    Category: def.node({
      description: def.string(),
      categoryName: def.string(),
      products: def.manyIn("PART_OF", "Product"),
    }),
    Supplier: def.node({
      country: def.string(),
      contactTitle: def.string(),
      address: def.string(),
      phone: def.string(),
      city: def.string(),
      contactName: def.string(),
      companyName: def.string(),
      postalCode: def.stringOrNull(),
      fax: def.stringOrNull(),
      region: def.stringOrNull(),
      homePage: def.stringOrNull(),
      products: def.manyOut("SUPPLIES", "Product"),
    }),
    SUPPLIES: def.relationship({}),
    PART_OF: def.relationship({}),
  });

export const loadNorthwindExample = async () => {
  const n0: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 18.0,
      unitsInStock: 39,
      reorderLevel: 10,
      discontinued: false,
      quantityPerUnit: "10 boxes x 20 bags",
      productName: "Chai",
      unitsOnOrder: 0,
    },
  };
  const n1: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 19.0,
      unitsInStock: 17,
      reorderLevel: 25,
      discontinued: false,
      quantityPerUnit: "24 - 12 oz bottles",
      productName: "Chang",
      unitsOnOrder: 40,
    },
  };
  const n2: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 10.0,
      unitsInStock: 13,
      reorderLevel: 25,
      discontinued: false,
      quantityPerUnit: "12 - 550 ml bottles",
      productName: "Aniseed Syrup",
      unitsOnOrder: 70,
    },
  };
  const n3: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 22.0,
      unitsInStock: 53,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "48 - 6 oz jars",
      productName: "Chef Anton's Cajun Seasoning",
      unitsOnOrder: 0,
    },
  };
  const n4: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 21.35,
      unitsInStock: 0,
      reorderLevel: 0,
      discontinued: true,
      quantityPerUnit: "36 boxes",
      productName: "Chef Anton's Gumbo Mix",
      unitsOnOrder: 0,
    },
  };
  const n5: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 25.0,
      unitsInStock: 120,
      reorderLevel: 25,
      discontinued: false,
      quantityPerUnit: "12 - 8 oz jars",
      productName: "Grandma's Boysenberry Spread",
      unitsOnOrder: 0,
    },
  };
  const n6: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitsInStock: 15,
      unitPrice: 30.0,
      reorderLevel: 10,
      discontinued: false,
      quantityPerUnit: "12 - 1 lb pkgs.",
      productName: "Uncle Bob's Organic Dried Pears",
      unitsOnOrder: 0,
    },
  };
  const n7: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitsInStock: 6,
      unitPrice: 40.0,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "12 - 12 oz jars",
      productName: "Northwoods Cranberry Sauce",
      unitsOnOrder: 0,
    },
  };
  const n8: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 97.0,
      unitsInStock: 29,
      reorderLevel: 0,
      discontinued: true,
      quantityPerUnit: "18 - 500 g pkgs.",
      productName: "Mishi Kobe Niku",
      unitsOnOrder: 0,
    },
  };
  const n9: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 31.0,
      unitsInStock: 31,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "12 - 200 ml jars",
      productName: "Ikura",
      unitsOnOrder: 0,
    },
  };
  const n10: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 21.0,
      unitsInStock: 22,
      reorderLevel: 30,
      discontinued: false,
      quantityPerUnit: "1 kg pkg.",
      productName: "Queso Cabrales",
      unitsOnOrder: 30,
    },
  };
  const n11: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 38.0,
      unitsInStock: 86,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "10 - 500 g pkgs.",
      productName: "Queso Manchego La Pastora",
      unitsOnOrder: 0,
    },
  };
  const n12: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 6.0,
      unitsInStock: 24,
      reorderLevel: 5,
      discontinued: false,
      quantityPerUnit: "2 kg box",
      productName: "Konbu",
      unitsOnOrder: 0,
    },
  };
  const n13: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 23.25,
      unitsInStock: 35,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "40 - 100 g pkgs.",
      productName: "Tofu",
      unitsOnOrder: 0,
    },
  };
  const n14: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 15.5,
      unitsInStock: 39,
      reorderLevel: 5,
      discontinued: false,
      quantityPerUnit: "24 - 250 ml bottles",
      productName: "Genen Shouyu",
      unitsOnOrder: 0,
    },
  };
  const n15: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 17.45,
      unitsInStock: 29,
      reorderLevel: 10,
      discontinued: false,
      quantityPerUnit: "32 - 500 g boxes",
      productName: "Pavlova",
      unitsOnOrder: 0,
    },
  };
  const n16: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 39.0,
      unitsInStock: 0,
      reorderLevel: 0,
      discontinued: true,
      quantityPerUnit: "20 - 1 kg tins",
      productName: "Alice Mutton",
      unitsOnOrder: 0,
    },
  };
  const n17: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 62.5,
      unitsInStock: 42,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "16 kg pkg.",
      productName: "Carnarvon Tigers",
      unitsOnOrder: 0,
    },
  };
  const n18: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitsInStock: 25,
      unitPrice: 9.2,
      reorderLevel: 5,
      discontinued: false,
      quantityPerUnit: "10 boxes x 12 pieces",
      productName: "Teatime Chocolate Biscuits",
      unitsOnOrder: 0,
    },
  };
  const n19: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 81.0,
      unitsInStock: 40,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "30 gift boxes",
      productName: "Sir Rodney's Marmalade",
      unitsOnOrder: 0,
    },
  };
  const n20: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 10.0,
      unitsInStock: 3,
      reorderLevel: 5,
      discontinued: false,
      quantityPerUnit: "24 pkgs. x 4 pieces",
      productName: "Sir Rodney's Scones",
      unitsOnOrder: 40,
    },
  };
  const n21: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 21.0,
      unitsInStock: 104,
      reorderLevel: 25,
      discontinued: false,
      quantityPerUnit: "24 - 500 g pkgs.",
      productName: "Gustaf's Knäckebröd",
      unitsOnOrder: 0,
    },
  };
  const n22: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 9.0,
      unitsInStock: 61,
      reorderLevel: 25,
      discontinued: false,
      quantityPerUnit: "12 - 250 g pkgs.",
      productName: "Tunnbröd",
      unitsOnOrder: 0,
    },
  };
  const n23: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 4.5,
      unitsInStock: 20,
      reorderLevel: 0,
      discontinued: true,
      quantityPerUnit: "12 - 355 ml cans",
      productName: "Guaraná Fantástica",
      unitsOnOrder: 0,
    },
  };
  const n24: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitsInStock: 76,
      unitPrice: 14.0,
      reorderLevel: 30,
      discontinued: false,
      quantityPerUnit: "20 - 450 g glasses",
      productName: "NuNuCa Nuß-Nougat-Creme",
      unitsOnOrder: 0,
    },
  };
  const n25: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 31.23,
      unitsInStock: 15,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "100 - 250 g bags",
      productName: "Gumbär Gummibärchen",
      unitsOnOrder: 0,
    },
  };
  const n26: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 43.9,
      unitsInStock: 49,
      reorderLevel: 30,
      discontinued: false,
      quantityPerUnit: "100 - 100 g pieces",
      productName: "Schoggi Schokolade",
      unitsOnOrder: 0,
    },
  };
  const n27: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 45.6,
      unitsInStock: 26,
      reorderLevel: 0,
      discontinued: true,
      quantityPerUnit: "25 - 825 g cans",
      productName: "Rössle Sauerkraut",
      unitsOnOrder: 0,
    },
  };
  const n28: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitsInStock: 0,
      unitPrice: 123.79,
      reorderLevel: 0,
      discontinued: true,
      quantityPerUnit: "50 bags x 30 sausgs.",
      productName: "Thüringer Rostbratwurst",
      unitsOnOrder: 0,
    },
  };
  const n29: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 25.89,
      unitsInStock: 10,
      reorderLevel: 15,
      discontinued: false,
      quantityPerUnit: "10 - 200 g glasses",
      productName: "Nord-Ost Matjeshering",
      unitsOnOrder: 0,
    },
  };
  const n30: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 12.5,
      unitsInStock: 0,
      reorderLevel: 20,
      discontinued: false,
      quantityPerUnit: "12 - 100 g pkgs",
      productName: "Gorgonzola Telino",
      unitsOnOrder: 70,
    },
  };
  const n31: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 32.0,
      unitsInStock: 9,
      reorderLevel: 25,
      discontinued: false,
      quantityPerUnit: "24 - 200 g pkgs.",
      productName: "Mascarpone Fabioli",
      unitsOnOrder: 40,
    },
  };
  const n32: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 2.5,
      unitsInStock: 112,
      reorderLevel: 20,
      discontinued: false,
      quantityPerUnit: "500 g",
      productName: "Geitost",
      unitsOnOrder: 0,
    },
  };
  const n33: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 14.0,
      unitsInStock: 111,
      reorderLevel: 15,
      discontinued: false,
      quantityPerUnit: "24 - 12 oz bottles",
      productName: "Sasquatch Ale",
      unitsOnOrder: 0,
    },
  };
  const n34: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 18.0,
      unitsInStock: 20,
      reorderLevel: 15,
      discontinued: false,
      quantityPerUnit: "24 - 12 oz bottles",
      productName: "Steeleye Stout",
      unitsOnOrder: 0,
    },
  };
  const n35: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 19.0,
      unitsInStock: 112,
      reorderLevel: 20,
      discontinued: false,
      quantityPerUnit: "24 - 250 g  jars",
      productName: "Inlagd Sill",
      unitsOnOrder: 0,
    },
  };
  const n36: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 26.0,
      unitsInStock: 11,
      reorderLevel: 25,
      discontinued: false,
      quantityPerUnit: "12 - 500 g pkgs.",
      productName: "Gravad lax",
      unitsOnOrder: 50,
    },
  };
  const n37: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 263.5,
      unitsInStock: 17,
      reorderLevel: 15,
      discontinued: false,
      quantityPerUnit: "12 - 75 cl bottles",
      productName: "Côte de Blaye",
      unitsOnOrder: 0,
    },
  };
  const n38: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 18.0,
      unitsInStock: 69,
      reorderLevel: 5,
      discontinued: false,
      quantityPerUnit: "750 cc per bottle",
      productName: "Chartreuse verte",
      unitsOnOrder: 0,
    },
  };
  const n39: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 18.4,
      unitsInStock: 123,
      reorderLevel: 30,
      discontinued: false,
      quantityPerUnit: "24 - 4 oz tins",
      productName: "Boston Crab Meat",
      unitsOnOrder: 0,
    },
  };
  const n40: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitsInStock: 85,
      unitPrice: 9.65,
      reorderLevel: 10,
      discontinued: false,
      quantityPerUnit: "12 - 12 oz cans",
      productName: "Jack's New England Clam Chowder",
      unitsOnOrder: 0,
    },
  };
  const n41: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitsInStock: 26,
      unitPrice: 14.0,
      reorderLevel: 0,
      discontinued: true,
      quantityPerUnit: "32 - 1 kg pkgs.",
      productName: "Singaporean Hokkien Fried Mee",
      unitsOnOrder: 0,
    },
  };
  const n42: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 46.0,
      unitsInStock: 17,
      reorderLevel: 25,
      discontinued: false,
      quantityPerUnit: "16 - 500 g tins",
      productName: "Ipoh Coffee",
      unitsOnOrder: 10,
    },
  };
  const n43: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 19.45,
      unitsInStock: 27,
      reorderLevel: 15,
      discontinued: false,
      quantityPerUnit: "20 - 2 kg bags",
      productName: "Gula Malacca",
      unitsOnOrder: 0,
    },
  };
  const n44: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 9.5,
      unitsInStock: 5,
      reorderLevel: 15,
      discontinued: false,
      quantityPerUnit: "1k pkg.",
      productName: "Rogede sild",
      unitsOnOrder: 70,
    },
  };
  const n45: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 12.0,
      unitsInStock: 95,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "4 - 450 g glasses",
      productName: "Spegesild",
      unitsOnOrder: 0,
    },
  };
  const n46: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 9.5,
      unitsInStock: 36,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "10 - 4 oz boxes",
      productName: "Zaanse koeken",
      unitsOnOrder: 0,
    },
  };
  const n47: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 12.75,
      unitsInStock: 15,
      reorderLevel: 25,
      discontinued: false,
      quantityPerUnit: "10 pkgs.",
      productName: "Chocolade",
      unitsOnOrder: 70,
    },
  };
  const n48: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 20.0,
      unitsInStock: 10,
      reorderLevel: 15,
      discontinued: false,
      quantityPerUnit: "24 - 50 g pkgs.",
      productName: "Maxilaku",
      unitsOnOrder: 60,
    },
  };
  const n49: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 16.25,
      unitsInStock: 65,
      reorderLevel: 30,
      discontinued: false,
      quantityPerUnit: "12 - 100 g bars",
      productName: "Valkoinen suklaa",
      unitsOnOrder: 0,
    },
  };
  const n50: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 53.0,
      unitsInStock: 20,
      reorderLevel: 10,
      discontinued: false,
      quantityPerUnit: "50 - 300 g pkgs.",
      productName: "Manjimup Dried Apples",
      unitsOnOrder: 0,
    },
  };
  const n51: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 7.0,
      unitsInStock: 38,
      reorderLevel: 25,
      discontinued: false,
      quantityPerUnit: "16 - 2 kg boxes",
      productName: "Filo Mix",
      unitsOnOrder: 0,
    },
  };
  const n52: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 32.8,
      unitsInStock: 0,
      reorderLevel: 0,
      discontinued: true,
      quantityPerUnit: "48 pieces",
      productName: "Perth Pasties",
      unitsOnOrder: 0,
    },
  };
  const n53: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 7.45,
      unitsInStock: 21,
      reorderLevel: 10,
      discontinued: false,
      quantityPerUnit: "16 pies",
      productName: "Tourtière",
      unitsOnOrder: 0,
    },
  };
  const n54: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 24.0,
      unitsInStock: 115,
      reorderLevel: 20,
      discontinued: false,
      quantityPerUnit: "24 boxes x 2 pies",
      productName: "Pâté chinois",
      unitsOnOrder: 0,
    },
  };
  const n55: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 38.0,
      unitsInStock: 21,
      reorderLevel: 30,
      discontinued: false,
      quantityPerUnit: "24 - 250 g pkgs.",
      productName: "Gnocchi di nonna Alice",
      unitsOnOrder: 10,
    },
  };
  const n56: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 19.5,
      unitsInStock: 36,
      reorderLevel: 20,
      discontinued: false,
      quantityPerUnit: "24 - 250 g pkgs.",
      productName: "Ravioli Angelo",
      unitsOnOrder: 0,
    },
  };
  const n57: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 13.25,
      unitsInStock: 62,
      reorderLevel: 20,
      discontinued: false,
      quantityPerUnit: "24 pieces",
      productName: "Escargots de Bourgogne",
      unitsOnOrder: 0,
    },
  };
  const n58: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 55.0,
      unitsInStock: 79,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "5 kg pkg.",
      productName: "Raclette Courdavault",
      unitsOnOrder: 0,
    },
  };
  const n59: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 34.0,
      unitsInStock: 19,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "15 - 300 g rounds",
      productName: "Camembert Pierrot",
      unitsOnOrder: 0,
    },
  };
  const n60: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 28.5,
      unitsInStock: 113,
      reorderLevel: 25,
      discontinued: false,
      quantityPerUnit: "24 - 500 ml bottles",
      productName: "Sirop d'érable",
      unitsOnOrder: 0,
    },
  };
  const n61: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 49.3,
      unitsInStock: 17,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "48 pies",
      productName: "Tarte au sucre",
      unitsOnOrder: 0,
    },
  };
  const n62: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 43.9,
      unitsInStock: 24,
      reorderLevel: 5,
      discontinued: false,
      quantityPerUnit: "15 - 625 g jars",
      productName: "Vegie-spread",
      unitsOnOrder: 0,
    },
  };
  const n63: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitsInStock: 22,
      unitPrice: 33.25,
      reorderLevel: 30,
      discontinued: false,
      quantityPerUnit: "20 bags x 4 pieces",
      productName: "Wimmers gute Semmelknödel",
      unitsOnOrder: 80,
    },
  };
  const n64: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitsInStock: 76,
      unitPrice: 21.05,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "32 - 8 oz bottles",
      productName: "Louisiana Fiery Hot Pepper Sauce",
      unitsOnOrder: 0,
    },
  };
  const n65: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 17.0,
      unitsInStock: 4,
      reorderLevel: 20,
      discontinued: false,
      quantityPerUnit: "24 - 8 oz jars",
      productName: "Louisiana Hot Spiced Okra",
      unitsOnOrder: 100,
    },
  };
  const n66: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 14.0,
      unitsInStock: 52,
      reorderLevel: 10,
      discontinued: false,
      quantityPerUnit: "24 - 12 oz bottles",
      productName: "Laughing Lumberjack Lager",
      unitsOnOrder: 0,
    },
  };
  const n67: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 12.5,
      unitsInStock: 6,
      reorderLevel: 15,
      discontinued: false,
      quantityPerUnit: "10 boxes x 8 pieces",
      productName: "Scottish Longbreads",
      unitsOnOrder: 10,
    },
  };
  const n68: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 36.0,
      unitsInStock: 26,
      reorderLevel: 15,
      discontinued: false,
      quantityPerUnit: "10 kg pkg.",
      productName: "Gudbrandsdalsost",
      unitsOnOrder: 0,
    },
  };
  const n69: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 15.0,
      unitsInStock: 15,
      reorderLevel: 30,
      discontinued: false,
      quantityPerUnit: "24 - 355 ml bottles",
      productName: "Outback Lager",
      unitsOnOrder: 10,
    },
  };
  const n70: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 21.5,
      unitsInStock: 26,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "10 - 500 g pkgs.",
      productName: "Flotemysost",
      unitsOnOrder: 0,
    },
  };
  const n71: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 34.8,
      unitsInStock: 14,
      reorderLevel: 0,
      discontinued: false,
      quantityPerUnit: "24 - 200 g pkgs.",
      productName: "Mozzarella di Giovanni",
      unitsOnOrder: 0,
    },
  };
  const n72: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 15.0,
      unitsInStock: 101,
      reorderLevel: 5,
      discontinued: false,
      quantityPerUnit: "24 - 150 g jars",
      productName: "Röd Kaviar",
      unitsOnOrder: 0,
    },
  };
  const n73: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 10.0,
      unitsInStock: 4,
      reorderLevel: 5,
      discontinued: false,
      quantityPerUnit: "5 kg pkg.",
      productName: "Longlife Tofu",
      unitsOnOrder: 20,
    },
  };
  const n74: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 7.75,
      unitsInStock: 125,
      reorderLevel: 25,
      discontinued: false,
      quantityPerUnit: "24 - 0.5 l bottles",
      productName: "Rhönbräu Klosterbier",
      unitsOnOrder: 0,
    },
  };
  const n75: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 18.0,
      unitsInStock: 57,
      reorderLevel: 20,
      discontinued: false,
      quantityPerUnit: "500 ml",
      productName: "Lakkalikööri",
      unitsOnOrder: 0,
    },
  };
  const n76: CreateNode = {
    type: "createNode",
    labels: ["Product"],
    properties: {
      unitPrice: 13.0,
      unitsInStock: 32,
      reorderLevel: 15,
      discontinued: false,
      quantityPerUnit: "12 boxes",
      productName: "Original Frankfurter grüne Soße",
      unitsOnOrder: 0,
    },
  };
  const n77: CreateNode = {
    type: "createNode",
    labels: ["Category"],
    properties: {
      description: "Soft drinks, coffees, teas, beers, and ales",
      categoryName: "Beverages",
    },
  };
  const n78: CreateNode = {
    type: "createNode",
    labels: ["Category"],
    properties: {
      description: "Sweet and savory sauces, relishes, spreads, and seasonings",
      categoryName: "Condiments",
    },
  };
  const n79: CreateNode = {
    type: "createNode",
    labels: ["Category"],
    properties: { description: "Desserts, candies, and sweet breads", categoryName: "Confections" },
  };
  const n80: CreateNode = {
    type: "createNode",
    labels: ["Category"],
    properties: { description: "Cheeses", categoryName: "Dairy Products" },
  };
  const n81: CreateNode = {
    type: "createNode",
    labels: ["Category"],
    properties: {
      description: "Breads, crackers, pasta, and cereal",
      categoryName: "Grains/Cereals",
    },
  };
  const n82: CreateNode = {
    type: "createNode",
    labels: ["Category"],
    properties: { description: "Prepared meats", categoryName: "Meat/Poultry" },
  };
  const n83: CreateNode = {
    type: "createNode",
    labels: ["Category"],
    properties: { description: "Dried fruit and bean curd", categoryName: "Produce" },
  };
  const n84: CreateNode = {
    type: "createNode",
    labels: ["Category"],
    properties: { description: "Seaweed and fish", categoryName: "Seafood" },
  };
  const n85: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "UK",
      contactTitle: "Purchasing Manager",
      address: "49 Gilbert St.",
      phone: "(171) 555-2222",
      city: "London",
      contactName: "Charlotte Cooper",
      companyName: "Exotic Liquids",
      postalCode: "EC1 4SD",
    },
  };
  const n86: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "USA",
      contactTitle: "Order Administrator",
      address: "P.O. Box 78934",
      phone: "(100) 555-4822",
      city: "New Orleans",
      contactName: "Shelley Burke",
      companyName: "New Orleans Cajun Delights",
      postalCode: "70117",
      region: "LA",
      homePage: "#CAJUN.HTM#",
    },
  };
  const n87: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "USA",
      contactTitle: "Sales Representative",
      address: "707 Oxford Rd.",
      phone: "(313) 555-5735",
      city: "Ann Arbor",
      contactName: "Regina Murphy",
      companyName: "Grandma Kelly's Homestead",
      postalCode: "48104",
      fax: "(313) 555-3349",
      region: "MI",
    },
  };
  const n88: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Japan",
      contactTitle: "Marketing Manager",
      address: "9-8 Sekimai Musashino-shi",
      phone: "(03) 3555-5011",
      city: "Tokyo",
      contactName: "Yoshi Nagase",
      companyName: "Tokyo Traders",
      postalCode: "100",
    },
  };
  const n89: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Spain",
      contactTitle: "Export Administrator",
      address: "Calle del Rosal 4",
      city: "Oviedo",
      phone: "(98) 598 76 54",
      contactName: "Antonio del Valle Saavedra",
      companyName: "Cooperativa de Quesos 'Las Cabras'",
      postalCode: "33007",
      region: "Asturias",
    },
  };
  const n90: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Japan",
      contactTitle: "Marketing Representative",
      address: "92 Setsuko Chuo-ku",
      phone: "(06) 431-7877",
      city: "Osaka",
      contactName: "Mayumi Ohno",
      companyName: "Mayumi's",
      postalCode: "545",
      homePage:
        "Mayumi's (on the World Wide Web)#http: //www.microsoft.com/accessdev/sampleapps/mayumi.htm#",
    },
  };
  const n91: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "3058",
      contactTitle: "Ian Devling",
      address: "Marketing Manager",
      phone: "Australia",
      city: "74 Rose St. Moonie Ponds",
      contactName: " Ltd.",
      companyName: "Pavlova",
      postalCode: "Victoria",
      fax: "(03) 444-2343",
      region: "Melbourne",
      homePage: "(03) 444-6588",
    },
  };
  const n92: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "M14 GSD",
      contactTitle: "Peter Wilson",
      address: "Sales Representative",
      city: "29 King's Way",
      phone: "UK",
      contactName: " Ltd.",
      companyName: "Specialty Biscuits",
      fax: "(161) 555-4448",
      region: "Manchester",
    },
  };
  const n93: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Sweden",
      contactTitle: "Sales Agent",
      address: "Kaloadagatan 13",
      phone: "031-987 65 43",
      city: "Göteborg",
      contactName: "Lars Peterson",
      companyName: "PB Knäckebröd AB",
      postalCode: "S-345 67",
      fax: "031-987 65 91",
    },
  };
  const n94: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Brazil",
      contactTitle: "Marketing Manager",
      address: "Av. das Americanas 12.890",
      phone: "(11) 555 4640",
      city: "Sao Paulo",
      contactName: "Carlos Diaz",
      companyName: "Refrescos Americanas LTDA",
      postalCode: "5442",
    },
  };
  const n95: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Germany",
      contactTitle: "Sales Manager",
      address: "Tiergartenstraße 5",
      phone: "(010) 9984510",
      city: "Berlin",
      contactName: "Petra Winkler",
      companyName: "Heli Süßwaren GmbH & Co. KG",
      postalCode: "10785",
    },
  };
  const n96: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Germany",
      contactTitle: "International Marketing Mgr.",
      address: "Bogenallee 51",
      city: "Frankfurt",
      phone: "(069) 992755",
      contactName: "Martin Bein",
      companyName: "Plutzer Lebensmittelgroßmärkte AG",
      postalCode: "60439",
      homePage:
        "Plutzer (on the World Wide Web)#http: //www.microsoft.com/accessdev/sampleapps/plutzer.htm#",
    },
  };
  const n97: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Germany",
      contactTitle: "Coordinator Foreign Markets",
      address: "Frahmredder 112a",
      phone: "(04721) 8713",
      city: "Cuxhaven",
      contactName: "Sven Petersen",
      postalCode: "27478",
      companyName: "Nord-Ost-Fisch Handelsgesellschaft mbH",
      fax: "(04721) 8714",
    },
  };
  const n98: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "48100",
      contactTitle: "Sales Representative",
      address: "Viale Dante",
      city: " 75",
      phone: "Italy",
      contactName: "Elio Rossi",
      companyName: "Formaggi Fortini s.r.l.",
      fax: "(0544) 60323",
      region: "Ravenna",
      homePage: "(0544) 60603",
    },
  };
  const n99: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Norway",
      contactTitle: "Marketing Manager",
      address: "Hatlevegen 5",
      city: "Sandvika",
      phone: "(0)2-953010",
      contactName: "Beate Vileid",
      companyName: "Norske Meierier",
      postalCode: "1320",
    },
  };
  const n100: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "USA",
      contactTitle: "Regional Account Rep.",
      address: "3400 - 8th Avenue Suite 210",
      phone: "(503) 555-9931",
      city: "Bend",
      contactName: "Cheryl Saylor",
      companyName: "Bigfoot Breweries",
      postalCode: "97101",
      region: "OR",
    },
  };
  const n101: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Sweden",
      contactTitle: "Sales Representative",
      address: "Brovallavägen 231",
      phone: "08-123 45 67",
      city: "Stockholm",
      contactName: "Michael Björn",
      companyName: "Svensk Sjöföda AB",
      postalCode: "S-123 45",
    },
  };
  const n102: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "75004",
      contactTitle: "Sales Manager",
      address: "203",
      phone: "France",
      city: " Rue des Francs-Bourgeois",
      contactName: "Guylène Nodier",
      companyName: "Aux joyeux ecclésiastiques",
      fax: "(1) 03.83.00.68",
      region: "Paris",
      homePage: "(1) 03.83.00.62",
    },
  };
  const n103: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "USA",
      contactTitle: "Wholesale Account Agent",
      address: "Order Processing Dept. 2100 Paul Revere Blvd.",
      city: "Boston",
      phone: "(617) 555-3267",
      contactName: "Robb Merchant",
      companyName: "New England Seafood Cannery",
      postalCode: "02134",
      fax: "(617) 555-3389",
      region: "MA",
    },
  };
  const n104: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "0512",
      contactTitle: "Owner",
      address: "471 Serangoon Loop",
      phone: "Singapore",
      city: " Suite #402",
      contactName: "Chandra Leka",
      companyName: "Leka Trading",
      fax: "555-8787",
      region: "Singapore",
    },
  };
  const n105: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Denmark",
      contactTitle: "Sales Manager",
      address: "Lyngbysild Fiskebakken 10",
      phone: "43844108",
      city: "Lyngby",
      contactName: "Niels Petersen",
      companyName: "Lyngbysild",
      postalCode: "2800",
      fax: "43844115",
    },
  };
  const n106: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Netherlands",
      contactTitle: "Accounting Manager",
      address: "Verkoop Rijnweg 22",
      phone: "(12345) 1212",
      city: "Zaandam",
      contactName: "Dirk Luchte",
      companyName: "Zaanse Snoepfabriek",
      postalCode: "9999 ZZ",
      fax: "(12345) 1210",
    },
  };
  const n107: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Finland",
      contactTitle: "Product Manager",
      address: "Valtakatu 12",
      city: "Lappeenranta",
      phone: "(953) 10956",
      contactName: "Anne Heikkonen",
      companyName: "Karkki Oy",
      postalCode: "53120",
    },
  };
  const n108: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "2042",
      contactTitle: "Wendy Mackenzie",
      address: "Sales Representative",
      phone: "Australia",
      city: "170 Prince Edward Parade Hunter's Hill",
      contactName: " Mate",
      companyName: "G'day",
      postalCode: "NSW",
      fax: "(02) 555-5914",
      region: "Sydney",
      homePage: "(02) 555-4873",
    },
  };
  const n109: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Canada",
      contactTitle: "Marketing Manager",
      address: "2960 Rue St. Laurent",
      city: "Montréal",
      phone: "(514) 555-9022",
      contactName: "Jean-Guy Lauzon",
      companyName: "Ma Maison",
      postalCode: "H1J 1C3",
      region: "Québec",
    },
  };
  const n110: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "84100",
      contactTitle: "Order Administrator",
      address: "Via dei Gelsomini",
      phone: "Italy",
      city: " 153",
      contactName: "Giovanni Giudici",
      companyName: "Pasta Buttini s.r.l.",
      fax: "(089) 6547665",
      region: "Salerno",
      homePage: "(089) 6547667",
    },
  };
  const n111: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "71300",
      contactTitle: "Sales Manager",
      address: "22",
      phone: "France",
      city: " rue H. Voiron",
      contactName: "Marie Delamare",
      companyName: "Escargots Nouveaux",
      fax: "85.57.00.07",
      region: "Montceau",
    },
  };
  const n112: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "74000",
      contactTitle: "Sales Representative",
      address: "Bat. B 3",
      phone: "France",
      city: " rue des Alpes",
      contactName: "Eliane Noz",
      companyName: "Gai pâturage",
      fax: "38.76.98.06",
      region: "Annecy",
      homePage: "38.76.98.58",
    },
  };
  const n113: CreateNode = {
    type: "createNode",
    labels: ["Supplier"],
    properties: {
      country: "Canada",
      contactTitle: "Accounting Manager",
      address: "148 rue Chasseur",
      city: "Ste-Hyacinthe",
      phone: "(514) 555-2955",
      contactName: "Chantal Goulet",
      companyName: "Forêts d'érables",
      postalCode: "J2S 7S8",
      fax: "(514) 555-2921",
      region: "Québec",
    },
  };

  await createNodes([
    n0,
    n1,
    n2,
    n3,
    n4,
    n5,
    n6,
    n7,
    n8,
    n9,
    n10,
    n11,
    n12,
    n13,
    n14,
    n15,
    n16,
    n17,
    n18,
    n19,
    n20,
    n21,
    n22,
    n23,
    n24,
    n25,
    n26,
    n27,
    n28,
    n29,
    n30,
    n31,
    n32,
    n33,
    n34,
    n35,
    n36,
    n37,
    n38,
    n39,
    n40,
    n41,
    n42,
    n43,
    n44,
    n45,
    n46,
    n47,
    n48,
    n49,
    n50,
    n51,
    n52,
    n53,
    n54,
    n55,
    n56,
    n57,
    n58,
    n59,
    n60,
    n61,
    n62,
    n63,
    n64,
    n65,
    n66,
    n67,
    n68,
    n69,
    n70,
    n71,
    n72,
    n73,
    n74,
    n75,
    n76,
    n77,
    n78,
    n79,
    n80,
    n81,
    n82,
    n83,
    n84,
    n85,
    n86,
    n87,
    n88,
    n89,
    n90,
    n91,
    n92,
    n93,
    n94,
    n95,
    n96,
    n97,
    n98,
    n99,
    n100,
    n101,
    n102,
    n103,
    n104,
    n105,
    n106,
    n107,
    n108,
    n109,
    n110,
    n111,
    n112,
    n113,
  ]);

  await createRelationships([
    { start: n85, end: n0, relationshipType: "SUPPLIES" },
    { start: n85, end: n1, relationshipType: "SUPPLIES" },
    { start: n85, end: n2, relationshipType: "SUPPLIES" },
    { start: n86, end: n3, relationshipType: "SUPPLIES" },
    { start: n86, end: n4, relationshipType: "SUPPLIES" },
    { start: n87, end: n5, relationshipType: "SUPPLIES" },
    { start: n87, end: n6, relationshipType: "SUPPLIES" },
    { start: n87, end: n7, relationshipType: "SUPPLIES" },
    { start: n88, end: n8, relationshipType: "SUPPLIES" },
    { start: n88, end: n9, relationshipType: "SUPPLIES" },
    { start: n89, end: n10, relationshipType: "SUPPLIES" },
    { start: n89, end: n11, relationshipType: "SUPPLIES" },
    { start: n90, end: n12, relationshipType: "SUPPLIES" },
    { start: n90, end: n13, relationshipType: "SUPPLIES" },
    { start: n90, end: n14, relationshipType: "SUPPLIES" },
    { start: n91, end: n15, relationshipType: "SUPPLIES" },
    { start: n91, end: n16, relationshipType: "SUPPLIES" },
    { start: n91, end: n17, relationshipType: "SUPPLIES" },
    { start: n92, end: n18, relationshipType: "SUPPLIES" },
    { start: n92, end: n19, relationshipType: "SUPPLIES" },
    { start: n92, end: n20, relationshipType: "SUPPLIES" },
    { start: n93, end: n21, relationshipType: "SUPPLIES" },
    { start: n93, end: n22, relationshipType: "SUPPLIES" },
    { start: n94, end: n23, relationshipType: "SUPPLIES" },
    { start: n95, end: n24, relationshipType: "SUPPLIES" },
    { start: n95, end: n25, relationshipType: "SUPPLIES" },
    { start: n95, end: n26, relationshipType: "SUPPLIES" },
    { start: n96, end: n27, relationshipType: "SUPPLIES" },
    { start: n96, end: n28, relationshipType: "SUPPLIES" },
    { start: n97, end: n29, relationshipType: "SUPPLIES" },
    { start: n98, end: n30, relationshipType: "SUPPLIES" },
    { start: n98, end: n31, relationshipType: "SUPPLIES" },
    { start: n99, end: n32, relationshipType: "SUPPLIES" },
    { start: n100, end: n33, relationshipType: "SUPPLIES" },
    { start: n100, end: n34, relationshipType: "SUPPLIES" },
    { start: n101, end: n35, relationshipType: "SUPPLIES" },
    { start: n101, end: n36, relationshipType: "SUPPLIES" },
    { start: n102, end: n37, relationshipType: "SUPPLIES" },
    { start: n102, end: n38, relationshipType: "SUPPLIES" },
    { start: n103, end: n39, relationshipType: "SUPPLIES" },
    { start: n103, end: n40, relationshipType: "SUPPLIES" },
    { start: n104, end: n41, relationshipType: "SUPPLIES" },
    { start: n104, end: n42, relationshipType: "SUPPLIES" },
    { start: n104, end: n43, relationshipType: "SUPPLIES" },
    { start: n105, end: n44, relationshipType: "SUPPLIES" },
    { start: n105, end: n45, relationshipType: "SUPPLIES" },
    { start: n106, end: n46, relationshipType: "SUPPLIES" },
    { start: n106, end: n47, relationshipType: "SUPPLIES" },
    { start: n107, end: n48, relationshipType: "SUPPLIES" },
    { start: n107, end: n49, relationshipType: "SUPPLIES" },
    { start: n108, end: n50, relationshipType: "SUPPLIES" },
    { start: n108, end: n51, relationshipType: "SUPPLIES" },
    { start: n108, end: n52, relationshipType: "SUPPLIES" },
    { start: n109, end: n53, relationshipType: "SUPPLIES" },
    { start: n109, end: n54, relationshipType: "SUPPLIES" },
    { start: n110, end: n55, relationshipType: "SUPPLIES" },
    { start: n110, end: n56, relationshipType: "SUPPLIES" },
    { start: n111, end: n57, relationshipType: "SUPPLIES" },
    { start: n112, end: n58, relationshipType: "SUPPLIES" },
    { start: n112, end: n59, relationshipType: "SUPPLIES" },
    { start: n113, end: n60, relationshipType: "SUPPLIES" },
    { start: n113, end: n61, relationshipType: "SUPPLIES" },
    { start: n91, end: n62, relationshipType: "SUPPLIES" },
    { start: n96, end: n63, relationshipType: "SUPPLIES" },
    { start: n86, end: n64, relationshipType: "SUPPLIES" },
    { start: n86, end: n65, relationshipType: "SUPPLIES" },
    { start: n100, end: n66, relationshipType: "SUPPLIES" },
    { start: n92, end: n67, relationshipType: "SUPPLIES" },
    { start: n99, end: n68, relationshipType: "SUPPLIES" },
    { start: n91, end: n69, relationshipType: "SUPPLIES" },
    { start: n99, end: n70, relationshipType: "SUPPLIES" },
    { start: n98, end: n71, relationshipType: "SUPPLIES" },
    { start: n101, end: n72, relationshipType: "SUPPLIES" },
    { start: n88, end: n73, relationshipType: "SUPPLIES" },
    { start: n96, end: n74, relationshipType: "SUPPLIES" },
    { start: n107, end: n75, relationshipType: "SUPPLIES" },
    { start: n96, end: n76, relationshipType: "SUPPLIES" },
    { start: n0, end: n77, relationshipType: "PART_OF" },
    { start: n1, end: n77, relationshipType: "PART_OF" },
    { start: n2, end: n78, relationshipType: "PART_OF" },
    { start: n3, end: n78, relationshipType: "PART_OF" },
    { start: n4, end: n78, relationshipType: "PART_OF" },
    { start: n5, end: n78, relationshipType: "PART_OF" },
    { start: n6, end: n83, relationshipType: "PART_OF" },
    { start: n7, end: n78, relationshipType: "PART_OF" },
    { start: n8, end: n82, relationshipType: "PART_OF" },
    { start: n9, end: n84, relationshipType: "PART_OF" },
    { start: n10, end: n80, relationshipType: "PART_OF" },
    { start: n11, end: n80, relationshipType: "PART_OF" },
    { start: n12, end: n84, relationshipType: "PART_OF" },
    { start: n13, end: n83, relationshipType: "PART_OF" },
    { start: n14, end: n78, relationshipType: "PART_OF" },
    { start: n15, end: n79, relationshipType: "PART_OF" },
    { start: n16, end: n82, relationshipType: "PART_OF" },
    { start: n17, end: n84, relationshipType: "PART_OF" },
    { start: n18, end: n79, relationshipType: "PART_OF" },
    { start: n19, end: n79, relationshipType: "PART_OF" },
    { start: n20, end: n79, relationshipType: "PART_OF" },
    { start: n21, end: n81, relationshipType: "PART_OF" },
    { start: n22, end: n81, relationshipType: "PART_OF" },
    { start: n23, end: n77, relationshipType: "PART_OF" },
    { start: n24, end: n79, relationshipType: "PART_OF" },
    { start: n25, end: n79, relationshipType: "PART_OF" },
    { start: n26, end: n79, relationshipType: "PART_OF" },
    { start: n27, end: n83, relationshipType: "PART_OF" },
    { start: n28, end: n82, relationshipType: "PART_OF" },
    { start: n29, end: n84, relationshipType: "PART_OF" },
    { start: n30, end: n80, relationshipType: "PART_OF" },
    { start: n31, end: n80, relationshipType: "PART_OF" },
    { start: n32, end: n80, relationshipType: "PART_OF" },
    { start: n33, end: n77, relationshipType: "PART_OF" },
    { start: n34, end: n77, relationshipType: "PART_OF" },
    { start: n35, end: n84, relationshipType: "PART_OF" },
    { start: n36, end: n84, relationshipType: "PART_OF" },
    { start: n37, end: n77, relationshipType: "PART_OF" },
    { start: n38, end: n77, relationshipType: "PART_OF" },
    { start: n39, end: n84, relationshipType: "PART_OF" },
    { start: n40, end: n84, relationshipType: "PART_OF" },
    { start: n41, end: n81, relationshipType: "PART_OF" },
    { start: n42, end: n77, relationshipType: "PART_OF" },
    { start: n43, end: n78, relationshipType: "PART_OF" },
    { start: n44, end: n84, relationshipType: "PART_OF" },
    { start: n45, end: n84, relationshipType: "PART_OF" },
    { start: n46, end: n79, relationshipType: "PART_OF" },
    { start: n47, end: n79, relationshipType: "PART_OF" },
    { start: n48, end: n79, relationshipType: "PART_OF" },
    { start: n49, end: n79, relationshipType: "PART_OF" },
    { start: n50, end: n83, relationshipType: "PART_OF" },
    { start: n51, end: n81, relationshipType: "PART_OF" },
    { start: n52, end: n82, relationshipType: "PART_OF" },
    { start: n53, end: n82, relationshipType: "PART_OF" },
    { start: n54, end: n82, relationshipType: "PART_OF" },
    { start: n55, end: n81, relationshipType: "PART_OF" },
    { start: n56, end: n81, relationshipType: "PART_OF" },
    { start: n57, end: n84, relationshipType: "PART_OF" },
    { start: n58, end: n80, relationshipType: "PART_OF" },
    { start: n59, end: n80, relationshipType: "PART_OF" },
    { start: n60, end: n78, relationshipType: "PART_OF" },
    { start: n61, end: n79, relationshipType: "PART_OF" },
    { start: n62, end: n78, relationshipType: "PART_OF" },
    { start: n63, end: n81, relationshipType: "PART_OF" },
    { start: n64, end: n78, relationshipType: "PART_OF" },
    { start: n65, end: n78, relationshipType: "PART_OF" },
    { start: n66, end: n77, relationshipType: "PART_OF" },
    { start: n67, end: n79, relationshipType: "PART_OF" },
    { start: n68, end: n80, relationshipType: "PART_OF" },
    { start: n69, end: n77, relationshipType: "PART_OF" },
    { start: n70, end: n80, relationshipType: "PART_OF" },
    { start: n71, end: n80, relationshipType: "PART_OF" },
    { start: n72, end: n84, relationshipType: "PART_OF" },
    { start: n73, end: n83, relationshipType: "PART_OF" },
    { start: n74, end: n77, relationshipType: "PART_OF" },
    { start: n75, end: n77, relationshipType: "PART_OF" },
    { start: n76, end: n78, relationshipType: "PART_OF" },
  ]);
};
